// Mock data for the application with real employee data
// In a real application, this would come from an API or database
import { Printer, Bath, DoorClosed, Coffee, Wifi } from "lucide-react"

// Real employee data organized by location based on the CSV file
const employeeData = {
  syracuse: [
    { name: "Jared Heinl, PE RLA", title: "Principal", email: "jheinl@beardsley.com", phone: "518-483-1585 4231" },
    { name: "Barry Halperin, R.A.", title: "Principal", email: "bhalperin@beardsley.com", phone: "315-472-6980 3311" },
    {
      name: "Thomas Ascienzo, LEED AP BD+C",
      title: "Electrical Senior Designer",
      email: "tascienzo@beardsley.com",
      phone: "315-472-6980 3323",
    },
    {
      name: "Seth Livermore, P.E.",
      title: "Civil Engineer V",
      email: "slivermore@beardsley.com",
      phone: "315-472-6980 3315",
    },
    {
      name: "Lillian Spencer",
      title: "Administrative Assistant",
      email: "lmarshall@beardsley.com",
      phone: "315-472-6980 3327",
    },
    {
      name: "Allie Henderson, P.E.",
      title: "Engineer IV",
      email: "ahenderson@beardsley.com",
      phone: "315-472-6980 3325",
    },
    { name: "Scott Folts", title: "Senior Architect", email: "sfolts@beardsley.com", phone: "315-253-7301" },
    {
      name: "Jacob Perez Gangi, EIT",
      title: "Structural Engineer II",
      email: "jperez@beardsley.com",
      phone: "315-472-6980",
    },
    {
      name: "Alex Clement, R.A. AIA",
      title: "Senior Architect",
      email: "aclement@beardsley.com",
      phone: "315-472-6980",
    },
    {
      name: "Nicholas Hartung",
      title: "Architectural Designer",
      email: "nhartung@beardsley.com",
      phone: "315-253-7301",
    },
    {
      name: "Chelsea Bush, P.E.",
      title: "Civil Engineer IV",
      email: "cbush@beardsley.com",
      phone: "315-472-6980 3312",
    },
    {
      name: "Michelle Thompson",
      title: "Assistant Controller",
      email: "mthompson@beardsley.com",
      phone: "315-253-7301 2241",
    },
    { name: "Brittany Varengo, R.A.", title: "Architect", email: "bvarengo@beardsley.com", phone: "315-472-6980 3314" },
    { name: "Caleb Sayers, R.A.", title: "Architect", email: "csayers@beardsley.com", phone: "315-472-6980 3320" },
    { name: "Justin Chiera, P.E.", title: "Civil Engineer IV", email: "jchiera@beardsley.com", phone: "315-472-6980" },
    {
      name: "Gabriel Amaya, P.E.",
      title: "Structural Engineer IV",
      email: "gamaya@beardsley.com",
      phone: "315-472-6980",
    },
    { name: "Adrianna Mondello", title: "Intern", email: "amondello@beardsley.com", phone: "315-472-6980 3320" },
  ],

  auburn: [
    {
      name: "Joanne Butler",
      title: "Landscape Senior Designer",
      email: "jbutler@beardsley.com",
      phone: "315-253-7301 2271",
    },
    {
      name: "Dan Whitman, CPD",
      title: "Plumbing Senior Designer",
      email: "dwhitman@beardsley.com",
      phone: "315-253-7301 2227",
    },
    {
      name: "Glenn Hewitt, CFPS, SET",
      title: "Fire Protection Senior Designer",
      email: "ghewitt@beardsley.com",
      phone: "315-253-7301 2254",
    },
    {
      name: "Kathy Quigley",
      title: "Computer System Administrator",
      email: "kquigley@beardsley.com",
      phone: "315-253-7301 2242",
    },
    {
      name: "Michael Picciano, P.E., LEED AP",
      title: "Electrical Engineer V",
      email: "mpicciano@beardsley.com",
      phone: "315-253-7301 2258",
    },
    {
      name: "Mark Rebich, P.E., LEED AP",
      title: "Principal",
      email: "mrebich@beardsley.com",
      phone: "315-253-7301 2261",
    },
    {
      name: "Dennis McCarthy, P.E., LEED AP",
      title: "Principal",
      email: "dmccarthy@beardsley.com",
      phone: "315-253-7301 2252",
    },
    {
      name: "Andrea DeLany, CBCP",
      title: "Mechanical Senior Designer",
      email: "adelany@beardsley.com",
      phone: "315-253-7301 2264",
    },
    {
      name: "Jeff Velte",
      title: "Structural Senior Designer",
      email: "jvelte@beardsley.com",
      phone: "315-253-7301 2232",
    },
    {
      name: "Andrew Ingram, R.L.A.",
      title: "Senior Landscape Architect",
      email: "dingram@beardsley.com",
      phone: "315-253-7301",
    },
    {
      name: "Paul Shrimpton",
      title: "Mechanical Senior Designer",
      email: "pshrimpton@beardsley.com",
      phone: "315-253-7301 2217",
    },
    {
      name: "Ed Onori",
      title: "Architectural Senior Designer",
      email: "eonori@beardsley.com",
      phone: "315-253-7301 2253",
    },
    {
      name: "Brandon Blumer",
      title: "Senior Electrical Designer",
      email: "bblumer@beardsley.com",
      phone: "315-253-7301 2297",
    },
    {
      name: "Kathy Mietz",
      title: "Administrative Assistant",
      email: "kmietz@beardsley.com",
      phone: "315-253-7301 2210",
    },
    { name: "Joe Kime, PE", title: "Principal", email: "jkime@beardsley.com", phone: "315-253-7301 2328" },
    {
      name: "Thomas Wight",
      title: "Business Development Manager",
      email: "twight@beardsley.com",
      phone: "315-253-7301 2222",
    },
    {
      name: "Doug Porter, P.E.",
      title: "Associate Principal",
      email: "dporter@beardsley.com",
      phone: "315-472-6980 3318",
    },
    { name: "Julia Furlong", title: "Marketing Manager", email: "jfurlong@beardsley.com", phone: "315-253-7301 2280" },
    {
      name: "Joanne Maddox Kinslow, AIA NYSCEO LEED Green Assoc",
      title: "Senior Architect",
      email: "jkinslow@beardsley.com",
      phone: "315-253-7301",
    },
    {
      name: "Phillip Beyel, PE",
      title: "Structural Engineer IV",
      email: "jbeyel@beardsley.com",
      phone: "315-253-7301 2274",
    },
    {
      name: "Tim McSweeney",
      title: "Electrical Designer",
      email: "tmcsweeney@beardsley.com",
      phone: "315-253-7301 2247",
    },
    {
      name: "Kurt Olsen, P.E.",
      title: "Mechanical Engineer V",
      email: "kolsen@beardsley.com",
      phone: "315-253-7301 2220",
    },
    { name: "Jason Coe, R.A.", title: "Senior Architect", email: "jcoe@beardsley.com", phone: "315-253-7301 2302" },
    { name: "John Hewitt, PE", title: "Mechanical Engineer V", email: "jhewitt@beardsley.com", phone: "315-253-7301" },
    {
      name: "Jared Bracken, R.A.",
      title: "Senior Architect",
      email: "jbracken@beardsley.com",
      phone: "315-253-7301 2211",
    },
    { name: "Felicia Fiacco", title: "Architectural Designer", email: "ffiacco@beardsley.com", phone: "315-253-7301" },
    {
      name: "Michael Naber, P.E.",
      title: "Structural Engineer IV",
      email: "mnaber@beardsley.com",
      phone: "315-253-7301 2273",
    },
    {
      name: "Tracey Carr",
      title: "Architectural Senior Designer",
      email: "tcarr@beardsley.com",
      phone: "315-253-7301 2216",
    },
    {
      name: "Kyle Daddario",
      title: "Architectural Designer",
      email: "kdaddario@beardsley.com",
      phone: "315-253-7301 2293",
    },
    { name: "Nathan Stultz", title: "Plumbing Designer", email: "nstultz@beardsley.com", phone: "315-253-7301 2228" },
    { name: "Mathew Milne", title: "Electrical Engineer I", email: "mathewrmilne@gmail.com", phone: "315-253-7301" },
    {
      name: "Dominic Seils",
      title: "Structural Intern Engineer",
      email: "dseils@beardsley.com",
      phone: "315-253-7301",
    },
    { name: "Joshua Marris", title: "Mechanical Engineer I", email: "jmarris@beardsley.com", phone: "315-253-7301" },
    { name: "Megan Litzenberger", title: "Accountant", email: "MLitzenberger@Beardsley.com", phone: "315-253-7301" },
    { name: "Samantha Brown", title: "Intern", email: "sbrown@beardsley.com", phone: "315-253-7301" },
    { name: "Evan Moore", title: "Intern", email: "emoore@beardsley.com", phone: "315-253-7301" },
  ],

  albany: [
    { name: "Cameron Beardsley", title: "Principal", email: "cbeardsley@beardsley.com", phone: "518-555-0100" },
    { name: "Caroline Beardsley", title: "Principal", email: "cabeardsley@beardsley.com", phone: "518-555-0101" },
    { name: "Catherine Beardsley", title: "Principal", email: "catbeardsley@beardsley.com", phone: "518-555-0102" },
    { name: "Charles Beardsley", title: "Principal", email: "chbeardsley@beardsley.com", phone: "518-555-0103" },
    { name: "Charlotte Beardsley", title: "Principal", email: "charbeardsley@beardsley.com", phone: "518-555-0104" },
    { name: "Christopher Beardsley", title: "Principal", email: "chrbeardsley@beardsley.com", phone: "518-555-0105" },
    { name: "Claire Beardsley", title: "Principal", email: "clbeardsley@beardsley.com", phone: "518-555-0106" },
    { name: "Daniel Beardsley", title: "Principal", email: "dbeardsley@beardsley.com", phone: "518-555-0107" },
    { name: "David Beardsley", title: "Principal", email: "dabeardsley@beardsley.com", phone: "518-555-0108" },
    { name: "Diana Beardsley", title: "Principal", email: "dibeardsley@beardsley.com", phone: "518-555-0109" },
  ],

  malone: [
    { name: "Edward Beardsley", title: "Principal", email: "ebeardsley@beardsley.com", phone: "518-555-0200" },
    { name: "Elizabeth Beardsley", title: "Principal", email: "elbeardsley@beardsley.com", phone: "518-555-0201" },
    { name: "Emily Beardsley", title: "Principal", email: "embeardsley@beardsley.com", phone: "518-555-0202" },
    { name: "Emma Beardsley", title: "Principal", email: "emmbeardsley@beardsley.com", phone: "518-555-0203" },
    { name: "Eric Beardsley", title: "Principal", email: "erbeardsley@beardsley.com", phone: "518-555-0204" },
    { name: "Ethan Beardsley", title: "Principal", email: "etbeardsley@beardsley.com", phone: "518-555-0205" },
  ],
}

const mockLocations = {
  syracuse: {
    id: "syracuse",
    name: "Syracuse Office",
    address: "1115 Solar Street, Ste 102 Syracuse, NY 13204",
    image: "/placeholder.svg?height=200&width=400",
    phone: "315-472-6980",
    hours: "Mon-Fri: 8:00 AM - 5:00 PM",
    wifi: "Syracuse-Office-Net",
    amenitiesList: [
      { name: "Printers (4)", icon: Printer },
      { name: "Restrooms", icon: Bath },
      { name: "Emergency Exits", icon: DoorClosed },
      { name: "Kitchen/Café", icon: Coffee },
      { name: "Conference Rooms (6)", icon: DoorClosed },
      { name: "Wi-Fi", icon: Wifi },
    ],
    quickLinks: [
      { name: "IT Support", url: "#", icon: Wifi },
      { name: "Book Room", url: "#" },
      { name: "Report Issue", url: "#" },
    ],
    floors: [
      {
        id: "floor-1",
        name: "Floor 1",
        rooms: [
          { id: "room-1", name: "Reception", x: 50, y: 50, width: 200, height: 100 },
          { id: "room-2", name: "Open Space", x: 50, y: 170, width: 500, height: 300 },
          { id: "room-3", name: "Meeting Room A", x: 300, y: 50, width: 150, height: 100 },
          { id: "room-4", name: "Meeting Room B", x: 470, y: 50, width: 150, height: 100 },
        ],
        amenities: [
          {
            id: "printer-1",
            type: "printer",
            name: "HP LaserJet Pro",
            ipAddress: "192.168.1.101",
            queueName: "SYR-PRINT-01",
            status: "Online",
            x: 450,
            y: 120,
          },
          { id: "restroom-1", type: "restroom", name: "Restroom", x: 450, y: 50 },
          { id: "exit-1", type: "exit", name: "Emergency Exit", x: 520, y: 50 },
          { id: "kitchen-1", type: "kitchen", name: "Kitchen", x: 520, y: 120 },
        ],
        seats: employeeData.syracuse.slice(0, 15).map((emp, index) => ({
          id: `seat-${index + 1}`,
          x: 80 + (index % 5) * 70,
          y: 200 + Math.floor(index / 5) * 70,
          rotation: 0,
          employee: {
            name: emp.name,
            title: emp.title,
            email: emp.email,
            phone: emp.phone,
            profileUrl: "#",
            avatar: "/placeholder.svg?height=40&width=40",
            notes: `Works at the Syracuse office.`,
          },
        })),
      },
    ],
  },
  albany: {
    id: "albany",
    name: "Albany Office",
    address: "69 State Street, Suite 1100D Albany, NY 12207",
    image: "/placeholder.svg?height=200&width=400",
    phone: "518-555-0100",
    hours: "Mon-Fri: 8:30 AM - 5:30 PM",
    wifi: "Albany-Office-Net",
    amenitiesList: [
      { name: "Printers (2)", icon: Printer },
      { name: "Restrooms", icon: Bath },
      { name: "Emergency Exits", icon: DoorClosed },
      { name: "Kitchen", icon: Coffee },
      { name: "Conference Rooms (3)", icon: DoorClosed },
      { name: "Wi-Fi", icon: Wifi },
    ],
    quickLinks: [
      { name: "IT Support", url: "#", icon: Wifi },
      { name: "Book Room", url: "#" },
      { name: "Report Issue", url: "#" },
    ],
    floors: [
      {
        id: "floor-1",
        name: "Floor 1",
        rooms: [
          { id: "room-1", name: "Lobby", x: 50, y: 50, width: 200, height: 100 },
          { id: "room-2", name: "Open Space", x: 50, y: 170, width: 400, height: 250 },
        ],
        amenities: [
          {
            id: "printer-1",
            type: "printer",
            name: "Brother MFC-L8900CDW",
            ipAddress: "192.168.2.101",
            queueName: "ALB-PRINT-01",
            status: "Online",
            x: 350,
            y: 120,
          },
          { id: "restroom-1", type: "restroom", name: "Restroom", x: 350, y: 50 },
          { id: "exit-1", type: "exit", name: "Emergency Exit", x: 420, y: 50 },
          { id: "kitchen-1", type: "kitchen", name: "Kitchen", x: 420, y: 120 },
        ],
        seats: employeeData.albany.map((emp, index) => ({
          id: `seat-${index + 1}`,
          x: 100 + (index % 4) * 80,
          y: 200 + Math.floor(index / 4) * 80,
          rotation: 0,
          employee: {
            name: emp.name,
            title: emp.title,
            email: emp.email,
            phone: emp.phone,
            profileUrl: "#",
            avatar: "/placeholder.svg?height=40&width=40",
            notes: `Works at the Albany office.`,
          },
        })),
      },
    ],
  },
  malone: {
    id: "malone",
    name: "Malone Office",
    address: "320 West Main St. Ste 2 Malone, NY 12953",
    image: "/placeholder.svg?height=200&width=400",
    phone: "518-555-0200",
    hours: "Mon-Fri: 8:00 AM - 5:00 PM",
    wifi: "Malone-Office-Net",
    amenitiesList: [
      { name: "Printers (1)", icon: Printer },
      { name: "Restrooms", icon: Bath },
      { name: "Emergency Exits", icon: DoorClosed },
      { name: "Kitchen", icon: Coffee },
      { name: "Conference Rooms (2)", icon: DoorClosed },
      { name: "Wi-Fi", icon: Wifi },
    ],
    quickLinks: [
      { name: "IT Support", url: "#", icon: Wifi },
      { name: "Book Room", url: "#" },
      { name: "Report Issue", url: "#" },
    ],
    floors: [
      {
        id: "floor-1",
        name: "Floor 1",
        rooms: [
          { id: "room-1", name: "Reception", x: 50, y: 50, width: 150, height: 100 },
          { id: "room-2", name: "Open Space", x: 220, y: 50, width: 300, height: 200 },
          { id: "room-3", name: "Conference Room", x: 50, y: 170, width: 150, height: 100 },
        ],
        amenities: [
          {
            id: "printer-1",
            type: "printer",
            name: "Canon PIXMA TR8620",
            ipAddress: "192.168.3.101",
            queueName: "MAL-PRINT-01",
            status: "Online",
            x: 450,
            y: 120,
          },
          { id: "restroom-1", type: "restroom", name: "Restroom", x: 450, y: 50 },
          { id: "exit-1", type: "exit", name: "Emergency Exit", x: 520, y: 50 },
          { id: "kitchen-1", type: "kitchen", name: "Kitchen", x: 520, y: 120 },
        ],
        seats: employeeData.malone.map((emp, index) => ({
          id: `seat-${index + 1}`,
          x: 250 + (index % 3) * 80,
          y: 100 + Math.floor(index / 3) * 80,
          rotation: 0,
          employee: {
            name: emp.name,
            title: emp.title,
            email: emp.email,
            phone: emp.phone,
            profileUrl: "#",
            avatar: "/placeholder.svg?height=40&width=40",
            notes: `Works at the Malone office.`,
          },
        })),
      },
    ],
  },
  auburn: {
    id: "auburn",
    name: "Auburn Office",
    address: "64 South Street, Auburn, NY 13021",
    image: "/placeholder.svg?height=200&width=400",
    phone: "315-555-3456",
    hours: "Mon-Fri: 8:00 AM - 5:30 PM",
    wifi: "Auburn-Office-Net",
    amenitiesList: [
      { name: "Printers (3)", icon: Printer },
      { name: "Restrooms", icon: Bath },
      { name: "Emergency Exits", icon: DoorClosed },
      { name: "Kitchen Areas (2)", icon: Coffee },
      { name: "Conference Rooms (3)", icon: DoorClosed },
      { name: "Wi-Fi", icon: Wifi },
    ],
    quickLinks: [
      { name: "IT Support", url: "#", icon: Wifi },
      { name: "Book Room", url: "#" },
      { name: "Report Issue", url: "#" },
    ],
    floors: [
      {
        id: "floor-1",
        name: "First Floor",
        rooms: [
          { id: "room-1", name: "Reception", x: 50, y: 50, width: 200, height: 150, type: "reception" },
          { id: "room-2", name: "Conference Room", x: 50, y: 220, width: 180, height: 120, type: "conference" },
          { id: "room-3", name: "Kitchen", x: 250, y: 50, width: 120, height: 100, type: "kitchen" },
          { id: "room-4", name: "Open Office", x: 250, y: 170, width: 300, height: 200, type: "office" },
          { id: "room-5", name: "Conference Room 2", x: 650, y: 50, width: 200, height: 120, type: "conference" },
          { id: "room-6", name: "Print Room", x: 650, y: 190, width: 100, height: 80, type: "print" },
          { id: "room-7", name: "Kitchen 2", x: 770, y: 190, width: 80, height: 80, type: "kitchen" },
          { id: "room-8", name: "Open Office 2", x: 650, y: 290, width: 350, height: 200, type: "office" },
          { id: "room-9", name: "Executive", x: 870, y: 50, width: 130, height: 120, type: "office" },
          { id: "room-10", name: "Restroom", x: 580, y: 50, width: 60, height: 80, type: "restroom" },
        ],
        amenities: [
          {
            id: "printer-1",
            type: "printer",
            name: "HP OfficeJet Pro 9015e",
            ipAddress: "192.168.4.101",
            queueName: "AUBURN-PRINT-01",
            status: "Online",
            x: 700,
            y: 230,
          },
          {
            id: "printer-2",
            type: "printer",
            name: "Canon PIXMA TR8620",
            ipAddress: "192.168.4.102",
            queueName: "AUBURN-PRINT-02",
            status: "Low Paper",
            x: 950,
            y: 80,
          },
          {
            id: "printer-3",
            type: "printer",
            name: "Brother HL-L3270CDW",
            ipAddress: "192.168.4.103",
            queueName: "AUBURN-PRINT-03",
            status: "Online",
            x: 310,
            y: 100,
          },
          { id: "restroom-1", type: "restroom", name: "Restroom", x: 610, y: 90 },
          { id: "exit-1", type: "exit", name: "Main Exit", x: 150, y: 80 },
          { id: "exit-2", type: "exit", name: "Emergency Exit", x: 950, y: 150 },
          { id: "kitchen-1", type: "kitchen", name: "Main Kitchen", x: 310, y: 100 },
          { id: "kitchen-2", type: "kitchen", name: "Break Room", x: 810, y: 230 },
          { id: "conference-1", type: "conference", name: "Conference Room A", x: 140, y: 280 },
          { id: "conference-2", type: "conference", name: "Conference Room B", x: 750, y: 110 },
        ],
        seats: employeeData.auburn.map((emp, index) => ({
          id: `seat-${index + 1}`,
          x: 280 + (index % 4) * 70,
          y: 200 + Math.floor(index / 4) * 70,
          rotation: 0,
          employee: {
            name: emp.name,
            title: emp.title,
            email: emp.email,
            phone: emp.phone,
            profileUrl: "#",
            avatar: "/placeholder.svg?height=40&width=40",
            notes: `Works at the Auburn office.`,
          },
        })),
      },
    ],
  },
}

export function getLocationData(locationId: string) {
  return mockLocations[locationId as keyof typeof mockLocations] || null
}
